
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.1'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = 'default';

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
    | 'asset'
    | 'band'
    | 'concert'
    | 'content_chunk'
    | 'location'
    | 'navigation_item'
    | 'page'
    | 'person'
    | 'playlist_song'
    | 'venue'
    | 'web_spotlight_root';

/**
 * Type representing all collections
 */
export type CollectionCodenames = 'default';

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = 'default';

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames = 'asset_type' | 'genre' | 'importance' | 'month' | 'vocation' | 'year';

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames = 'archived' | 'draft' | 'published' | 'scheduled';

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
    | 'alt_text'
    | 'artist'
    | 'asset_file'
    | 'asset_title'
    | 'asset_type'
    | 'band_bio'
    | 'band_genre'
    | 'band_logo'
    | 'band_member'
    | 'band_name'
    | 'band_playlist'
    | 'city'
    | 'content'
    | 'directions'
    | 'event_date'
    | 'first_name'
    | 'hero_image'
    | 'last_name'
    | 'lead_paragraph'
    | 'location'
    | 'promotional_image'
    | 'show_in_navigation'
    | 'social_media'
    | 'song_link'
    | 'song_title'
    | 'state_province'
    | 'street_address'
    | 'subpages'
    | 'supporting_act__supporting_act'
    | 'supporting_artist'
    | 'telephone_number'
    | 'text'
    | 'ticket_purchasing'
    | 'title'
    | 'untitled_rich_text'
    | 'url'
    | 'venue_name'
    | 'vocation'
    | 'zipcode';
