
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/


                /**
 * Type representing all languages
*/
                export type LanguageCodenames = 'Chinese_(Traditional)' | 'default' | 'zh_cn' | 'zh_Hant' | 'zh-Hant';

                /**
 * Type representing all content types
*/
                export type ContentTypeCodenames = 'asset' | 'band' | 'concert_review' | 'concert' | 'content_chunk' | 'location' | 'navigation_item' | 'page' | 'person' | 'playlist_song' | 'venue' | 'web_spotlight_root';

                /**
 * Type representing all collections
*/
                export type CollectionCodenames = 'default' | 'reviews';

                /**
 * Type representing all workflows
*/
                export type WorkflowCodenames = 'default';

                /**
 * Type representing all taxonomies
*/
                export type TaxonomyCodenames = 'asset_type' | 'genre' | 'importance' | 'month' | 'vocation' | 'year';

                /**
 * Type representing all worksflow steps across all workflows
*/
                export type WorkflowStepCodenames = 'archived' | 'draft' | 'published' | 'scheduled';

                 /**
 * Type representing all element codenames across all content types
*/
                export type ElementCodenames = 'alt_text' | 'artist_name' | 'asset_file' | 'asset_title' | 'asset_type' | 'author' | 'band_bio' | 'band_genre' | 'band_logo' | 'band_member' | 'band_name' | 'band_playlist' | 'city' | 'concert' | 'content' | 'directions' | 'event_date' | 'first_name' | 'headline' | 'hero_image' | 'last_name' | 'lead_paragraph' | 'location' | 'promotional_image' | 'review_body' | 'show_in_navigation' | 'slug' | 'social_media' | 'song_link' | 'song_title' | 'state_province' | 'street_address' | 'subpages' | 'supporting_act__supporting_act' | 'supporting_artist' | 'telephone_number' | 'ticket_purchasing' | 'title' | 'untitled_rich_text' | 'untitled_url_slug' | 'url' | 'venue_name' | 'vocation' | 'zipcode';
            