
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.1'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '@models/system/index.js';

/**
 * Content Chunk
 *
 * Id: a797ce49-151e-4ecf-a12c-2a34ef9cd750
 * Codename: content_chunk
 */
export type ContentChunk = CoreContentType<
    ContentChunkElementCodenames,
    {
        /**
         * Text
         *
         * Type: text
         * Required: false
         * Codename: text
         * Id: 98af177e-2f08-4b63-a724-3d6eabb9071f
         */
        readonly text: Elements.TextElement;
    },
    'content_chunk'
>;

/**
 * Type representing all available element codenames for Content Chunk
 */
export type ContentChunkElementCodenames = 'text';

/**
 * Type guard for Content Chunk
 *
 * Id: a797ce49-151e-4ecf-a12c-2a34ef9cd750
 * Codename: content_chunk
 */
export function isContentChunk(item: CoreContentType | undefined | null): item is ContentChunk {
    return item?.system?.type === 'content_chunk';
}
