
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.1'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { Company_band } from './index';
import type { CoreContentType } from '@models/system/index';

/**
 * Playlist Song
 *
 * Id: 57460815-6e85-43cf-a5d0-beed1cd3838a
 * Codename: playlist_song
 */
export type PlaylistSong = CoreContentType<
    PlaylistSongElementCodenames,
    {
        /**
         * Song Title
         *
         * Type: text
         * Required: true
         * Codename: song_title
         * Id: 6109c742-03ab-4f64-877e-8c5570c0e3a2
         * Guidelines: Title of the song.
         */
        readonly song_title: Elements.TextElement;
        /**
         * Artist
         *
         * Type: modular_content
         * Required: true
         * Codename: artist
         * Id: 0a911b05-3385-4d06-934e-8bde873498ab
         * Guidelines: Link to performing artist
         */
        readonly artist: Elements.LinkedItemsElement<Company_band>;
        /**
         * Song Link
         *
         * Type: text
         * Required: true
         * Codename: song_link
         * Id: 5636bbde-0d01-498e-8c1c-dffef0405980
         * Guidelines: Link to the song url (i.e. youtube, etc.)
         */
        readonly song_link: Elements.TextElement;
    },
    'playlist_song'
>;

/**
 * Type representing all available element codenames for Playlist Song
 */
export type PlaylistSongElementCodenames = 'song_title' | 'artist' | 'song_link';

/**
 * Type guard for Playlist Song
 *
 * Id: 57460815-6e85-43cf-a5d0-beed1cd3838a
 * Codename: playlist_song
 */
export function isPlaylistSong(item: CoreContentType | undefined | null): item is PlaylistSong {
    return item?.system?.type === 'playlist_song';
}
